"""empty message

Revision ID: e57fa33c44d1
Revises: f21909ad156e
Create Date: 2021-10-12 07:17:20.884959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57fa33c44d1'
down_revision = 'f21909ad156e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'available_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('available_products', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
